module.exports = {
  type: 'mysql',
  // host: 'localhost',
  host: 'grp6m5lz95d9exiz.cbetxkdyhwsb.us-east-1.rds.amazonaws.com',
  port: 3306,
  // username: 'brechore_api',
  // password: 'E1fc3b6@!',
  // database: 'brechore_db',
  // username: 'root',
  // password: 'e1fc3b62',
  // database: 'restore',
  username: 't4rh61y2mn9b24z2',
  password: 'd5f3pyq6zefgf2wk',
  database: 'p322gwo28a6b4don',
  entities: ['./src/models/*.ts'],
  migrations: ['./src/database/migrations/*.ts'],
  cli: {
    migrationsDir: './src/database/migrations',
  },
  // entities: [__dirname + '/dist/models/*.js'],
  // migrations: ['./dist/database/migrations/*.js'],
};
